// Auto-generated by assemble-apps.sh - DO NOT EDIT
import type { CustomNavSection } from '@/lib/customRouteTypes'

export const customNavSections: CustomNavSection[] = [
    // Nav sections from company-portal
    {
      key: "company-portal",
      title: "company-portal",
      scope: 'primary',
      position: 10,
      items: []
    },

    // Nav sections from customer-portal
    {
      key: "customer-portal",
      title: "customer-portal",
      scope: 'primary',
      position: 10,
      items: []
    },

]

export default customNavSections
