// Auto-generated by assemble-apps.sh - DO NOT EDIT
import type { CustomRouteDefinition } from '@/lib/customRouteTypes'

export const customRoutes: CustomRouteDefinition[] = [
    // Routes from company-portal
    {
      path: "/company-portal",
      component: "./src/pages/OperatorDashboardPage.tsx",
      minRole: "operator"
    },
    {
      path: "/company-portal/queue",
      component: "./src/pages/SupportQueuePage.tsx",
      minRole: "operator"
    },

    // Routes from customer-portal
    {
      path: "/customer-portal",
      component: "./src/pages/MemberDashboardPage.tsx",
      minRole: "member"
    },
    {
      path: "/customer-portal/knowledge",
      component: "./src/pages/KnowledgePage.tsx",
      minRole: "member"
    },

]

// Transform our custom routes to the format expected by the core
const transformedRoutes: CustomRouteDefinition[] = customRoutes.map(route => ({
  path: route.path,
  component: route.component,
  minRole: route.min_role
}))

export default transformedRoutes
