// Auto-generated by assemble-apps.sh - DO NOT EDIT
import type { CustomRouteDefinition } from '@/lib/customRouteTypes'

export const customRoutes: CustomRouteDefinition[] = [
    // Routes from company-portal
    {
      path: "/company-portal",
      loader: () => import('@custom/company-portal/src/pages/OperatorDashboardPage.tsx'),
      minRole: "operator"
    },
    {
      path: "/company-portal/queue",
      loader: () => import('@custom/company-portal/src/pages/SupportQueuePage.tsx'),
      minRole: "operator"
    },
    {
      path: "/company-portal/cases/:caseId",
      loader: () => import('@custom/company-portal/src/pages/CaseWorkspacePage.tsx'),
      minRole: "operator"
    },
    {
      path: "/company-portal/knowledge",
      loader: () => import('@custom/company-portal/src/pages/KnowledgeListPage.tsx'),
      minRole: "operator"
    },
    {
      path: "/company-portal/knowledge/:articleId",
      loader: () => import('@custom/company-portal/src/pages/KnowledgeEditorPage.tsx'),
      minRole: "operator"
    },
    {
      path: "/company-portal/knowledge/new",
      loader: () => import('@custom/company-portal/src/pages/KnowledgeEditorPage.tsx'),
      minRole: "operator"
    },
    {
      path: "/company-portal/community",
      loader: () => import('@custom/company-portal/src/pages/CommunityModerationPage.tsx'),
      minRole: "operator"
    },
    {
      path: "/company-portal/analytics",
      loader: () => import('@custom/company-portal/src/pages/AnalyticsPage.tsx'),
      minRole: "operator"
    },
    {
      path: "/company-portal/users",
      loader: () => import('@custom/company-portal/src/pages/UsersPage.tsx'),
      minRole: "operator"
    },

    // Routes from customer-portal
    {
      path: "/customer-portal",
      loader: () => import('@custom/customer-portal/src/pages/MemberDashboardPage.tsx'),
      minRole: "member"
    },
    {
      path: "/customer-portal/knowledge",
      loader: () => import('@custom/customer-portal/src/pages/KnowledgePage.tsx'),
      minRole: "member"
    },
    {
      path: "/customer-portal/knowledge/:articleId",
      loader: () => import('@custom/customer-portal/src/pages/KnowledgeArticlePage.tsx'),
      minRole: "member"
    },
    {
      path: "/customer-portal/support",
      loader: () => import('@custom/customer-portal/src/pages/SupportPage.tsx'),
      minRole: "member"
    },
    {
      path: "/customer-portal/support/cases/:caseId",
      loader: () => import('@custom/customer-portal/src/pages/SupportCasesPage.tsx'),
      minRole: "member"
    },
    {
      path: "/customer-portal/community",
      loader: () => import('@custom/customer-portal/src/pages/CommunityPage.tsx'),
      minRole: "member"
    },
    {
      path: "/customer-portal/community/:postId",
      loader: () => import('@custom/customer-portal/src/pages/CommunityPostPage.tsx'),
      minRole: "member"
    },

]

export default customRoutes
