#!/usr/bin/env bash
# assemble-apps-simple.sh — Simple version without Node.js complications
# Manually extracts routes and nav from JSON manifests using sed/grep

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

CUSTOM_DIR="$PROJECT_ROOT/custom"
MANIFEST_DIR="$CUSTOM_DIR/manifest"

echo "🔧 Assembling apps → $MANIFEST_DIR"

# 1. Ensure manifest directory exists
mkdir -p "$MANIFEST_DIR"

# 2. Find all spine-app.json files
APP_MANIFESTS=()
while IFS= read -r -d '' manifest; do
    APP_MANIFESTS+=("$manifest")
done < <(find "$CUSTOM_DIR" -name "spine-app.json" -type f -print0 | sort -z)

if [ ${#APP_MANIFESTS[@]} -eq 0 ]; then
    echo "  ○ No app manifests found"
    # Create empty files
    cat > "$MANIFEST_DIR/routes.ts" << 'EOF'
import type { CustomRouteDefinition } from '@/lib/customRouteTypes'

export const customRoutes: CustomRouteDefinition[] = []

export default customRoutes
EOF
    cat > "$MANIFEST_DIR/navSections.ts" << 'EOF'
import type { CustomNavSection } from '@/lib/customRouteTypes'

export const customNavSections: CustomNavSection[] = []

export default customNavSections
EOF
    echo "✅ Done (empty manifests)"
    exit 0
fi

echo "  ✓ Found ${#APP_MANIFESTS[@]} app manifests"

# 3. Generate routes.ts manually
echo "  📝 Generating routes..."
cat > "$MANIFEST_DIR/routes.ts" << 'EOF'
// Auto-generated by assemble-apps.sh - DO NOT EDIT
import type { CustomRouteDefinition } from '@/lib/customRouteTypes'

export const customRoutes: CustomRouteDefinition[] = [
EOF

for manifest in "${APP_MANIFESTS[@]}"; do
    app_dir=$(dirname "$manifest")
    app_slug=$(basename "$app_dir")
    
    echo "    // Routes from $app_slug" >> "$MANIFEST_DIR/routes.ts"
    
    # Extract routes using simple text processing
    # This is a simplified approach - in production you'd want proper JSON parsing
    awk '/routes/,/\],/' "$manifest" | grep -E '"path"|"component"|"min_role"' | while IFS= read -r line; do
        if [[ $line == *"path"* ]]; then
            path=$(echo "$line" | sed 's/.*"path": *"\([^"]*\)".*/\1/')
        elif [[ $line == *"component"* ]]; then
            component=$(echo "$line" | sed 's/.*"component": *"\([^"]*\)".*/\1/')
        elif [[ $line == *"min_role"* ]]; then
            min_role=$(echo "$line" | sed 's/.*"min_role": *"\([^"]*\)".*/\1/')
            # Output the route object
            echo "    {" >> "$MANIFEST_DIR/routes.ts"
            echo "      path: \"$path\"," >> "$MANIFEST_DIR/routes.ts"
            echo "      loader: () => import('./$app_slug/${component#./}')," >> "$MANIFEST_DIR/routes.ts"
            echo "      minRole: \"$min_role\"" >> "$MANIFEST_DIR/routes.ts"
            echo "    }," >> "$MANIFEST_DIR/routes.ts"
        fi
    done
    echo "" >> "$MANIFEST_DIR/routes.ts"
done

cat >> "$MANIFEST_DIR/routes.ts" << 'EOF'
]

// Transform our custom routes to the format expected by the core
const transformedRoutes: CustomRouteDefinition[] = customRoutes.map(route => ({
  path: route.path,
  component: route.component,
  minRole: route.minRole
}))

export default transformedRoutes
EOF

# 4. Generate navSections.ts manually
echo "  📝 Generating navigation sections..."
cat > "$MANIFEST_DIR/navSections.ts" << 'EOF'
// Auto-generated by assemble-apps.sh - DO NOT EDIT
import type { CustomNavSection } from '@/lib/customRouteTypes'

export const customNavSections: CustomNavSection[] = [
EOF

for manifest in "${APP_MANIFESTS[@]}"; do
    app_dir=$(dirname "$manifest")
    app_slug=$(basename "$app_dir")
    
    echo "    // Nav sections from $app_slug" >> "$MANIFEST_DIR/navSections.ts"
    
    # For now, just add a placeholder - full nav parsing would be more complex
    echo "    {" >> "$MANIFEST_DIR/navSections.ts"
    echo "      key: \"$app_slug\"," >> "$MANIFEST_DIR/navSections.ts"
    echo "      title: \"$app_slug\"," >> "$MANIFEST_DIR/navSections.ts"
    echo "      scope: 'primary'," >> "$MANIFEST_DIR/navSections.ts"
    echo "      position: 10," >> "$MANIFEST_DIR/navSections.ts"
    echo "      items: []" >> "$MANIFEST_DIR/navSections.ts"
    echo "    }," >> "$MANIFEST_DIR/navSections.ts"
    echo "" >> "$MANIFEST_DIR/navSections.ts"
done

cat >> "$MANIFEST_DIR/navSections.ts" << 'EOF'
]

export default customNavSections
EOF

echo "  ✓ Generated routes: $(grep -c 'path:' "$MANIFEST_DIR/routes.ts" || echo "0") routes"
echo "  ✓ Generated nav: $(grep -c 'title:' "$MANIFEST_DIR/navSections.ts" || echo "0") sections"
echo "✅ Done"
