#!/usr/bin/env bash
# assemble-apps.sh — Generate custom routes and nav sections from app manifests
# Scans custom/*/spine-app.json files and assembles them into custom/manifest/
# This replaces hand-edited routes.ts and navSections.ts with auto-generated versions

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

CUSTOM_DIR="$PROJECT_ROOT/custom"
MANIFEST_DIR="$CUSTOM_DIR/manifest"
TARGET_ROUTES="$MANIFEST_DIR/routes.ts"
TARGET_NAV="$MANIFEST_DIR/navSections.ts"

echo "🔧 Assembling apps → $MANIFEST_DIR"

# 1. Ensure manifest directory exists
mkdir -p "$MANIFEST_DIR"

# 2. Find all spine-app.json files
APP_MANIFESTS=()
while IFS= read -r -d '' manifest; do
    APP_MANIFESTS+=("$manifest")
done < <(find "$CUSTOM_DIR" -name "spine-app.json" -type f -print0 | sort -z)

if [ ${#APP_MANIFESTS[@]} -eq 0 ]; then
    echo "  ○ No app manifests found"
    # Create empty files
    cat > "$TARGET_ROUTES" << 'EOF'
import type { CustomRouteDefinition } from '@/lib/customRouteTypes'

export const customRoutes: CustomRouteDefinition[] = []

export default customRoutes
EOF
    cat > "$TARGET_NAV" << 'EOF'
import type { CustomNavSection } from '@/lib/customRouteTypes'

export const customNavSections: CustomNavSection[] = []

export default customNavSections
EOF
    echo "✅ Done (empty manifests)"
    exit 0
fi

echo "  ✓ Found ${#APP_MANIFESTS[@]} app manifests"

# 3. Generate routes.ts
echo "  📝 Generating routes..."
cat > "$CUSTOM_DIR/manifest/routes.ts" << 'EOF'
// Auto-generated by assemble-apps.sh - DO NOT EDIT
import type { CustomRouteDefinition } from '@/lib/customRouteTypes'

export const customRoutes: CustomRouteDefinition[] = [
EOF

# Use Node.js to parse JSON since jq is not available
node << 'EOF'
const fs = require('fs');
const path = require('path');

// Find all spine-app.json files
const manifestPaths = [];
const customDir = './custom';

function findManifests(dir) {
  const items = fs.readdirSync(dir, { withFileTypes: true });
  for (const item of items) {
    const fullPath = path.join(dir, item.name);
    if (item.isDirectory()) {
      findManifests(fullPath);
    } else if (item.name === 'spine-app.json') {
      manifestPaths.push(fullPath);
    }
  }
}

findManifests(customDir);

manifestPaths.forEach(manifestPath => {
  try {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    const appSlug = path.basename(path.dirname(manifestPath));
    
    if (manifest.routes && Array.isArray(manifest.routes)) {
      console.log('    // Routes from ' + appSlug);
      manifest.routes.forEach(route => {
        if (route.path && route.component) {
          const routeJson = JSON.stringify(route);
          console.log('    ' + routeJson + ',');
        }
      });
      console.log('');
    }
  } catch (err) {
    console.error('Error processing', manifestPath, err.message);
  }
});
EOF >> "$CUSTOM_DIR/manifest/routes.ts"

cat >> "$CUSTOM_DIR/manifest/routes.ts" << 'EOF'
]

// Transform our custom routes to the format expected by the core
const transformedRoutes: CustomRouteDefinition[] = customRoutes.map(route => ({
  path: route.path,
  component: route.component,
  minRole: route.min_role
}))

export default transformedRoutes
EOF

# 4. Generate navSections.ts
echo "  📝 Generating navigation sections..."
cat > "$CUSTOM_DIR/manifest/navSections.ts" << 'EOF'
// Auto-generated by assemble-apps.sh - DO NOT EDIT
import type { CustomNavSection } from '@/lib/customRouteTypes'

export const customNavSections: CustomNavSection[] = [
EOF

# Use Node.js to parse JSON for nav sections
node << 'EOF'
const fs = require('fs');
const path = require('path');

// Find all spine-app.json files
const manifestPaths = [];
const customDir = './custom';

function findManifests(dir) {
  const items = fs.readdirSync(dir, { withFileTypes: true });
  for (const item of items) {
    const fullPath = path.join(dir, item.name);
    if (item.isDirectory()) {
      findManifests(fullPath);
    } else if (item.name === 'spine-app.json') {
      manifestPaths.push(fullPath);
    }
  }
}

findManifests(customDir);

manifestPaths.forEach(manifestPath => {
  try {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    const appSlug = path.basename(path.dirname(manifestPath));
    
    if (manifest.nav_sections && Array.isArray(manifest.nav_sections)) {
      console.log('    // Nav sections from ' + appSlug);
      manifest.nav_sections.forEach(navSection => {
        if (navSection.key && navSection.items) {
          const navJson = JSON.stringify(navSection);
          console.log('    ' + navJson + ',');
        }
      });
      console.log('');
    }
  } catch (err) {
    console.error('Error processing', manifestPath, err.message);
  }
});
EOF >> "$CUSTOM_DIR/manifest/navSections.ts"

cat >> "$CUSTOM_DIR/manifest/navSections.ts" << 'EOF'
]

export default customNavSections
EOF

echo "  ✓ Generated routes: $(grep -c 'path:' "$CUSTOM_DIR/manifest/routes.ts" || echo "0") routes"
echo "  ✓ Generated nav: $(grep -c 'title:' "$CUSTOM_DIR/manifest/navSections.ts" || echo "0") sections"
echo "✅ Done"
